### ISSUE TITLE
Learn

### ISSUE THREAD

**Issue by keensam04** [keensam04/ufh#6]
**Tasks**
- [x] complete this [quick tutorial on maven](https://spring.io/guides/gs/maven/)
- [ ] read atleast chapter 1 of this [git ebook](https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control)
- [x] go through this [JSON tutorial](https://beginnersbook.com/2015/04/json-tutorial/). *Skip if you already know what json is*
- [ ] complete this [quick tutorial on spring boot](https://spring.io/guides/gs/spring-boot/)
- [ ] complete this [quick tutorial on building RESTful services](https://spring.io/guides/gs/rest-service/)
